import HTMLDSL

/// Auto Generated by `figma-export colors`.
/// Don’t edit this file manually to avoid runtime crashes.
public extension Color {
    
    static var buttonOnMedia: Color { .rgba(red: 0.125, green: 0.125, blue: 0.161, alpha: 1.000) }
    
    static var categoryHover: Color { .rgba(red: 0.962, green: 0.962, blue: 0.962, alpha: 1.000) }
    
    static var categorySelected: Color { .rgba(red: 0.949, green: 0.953, blue: 0.953, alpha: 1.000) }
    
    static var divider: Color { .rgba(red: 0.906, green: 0.902, blue: 0.902, alpha: 1.000) }
    
    static var textPlaceholder: Color { .rgba(red: 0.512, green: 0.512, blue: 0.512, alpha: 1.000) }
    
    static var textPrimary: Color { .rgba(red: 0.184, green: 0.192, blue: 0.200, alpha: 1.000) }
    
    static var textSecondary: Color { .rgba(red: 0.312, green: 0.312, blue: 0.312, alpha: 1.000) }
    
    static var white: Color { .rgba(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000) }
    
}